
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action SettingsAction;

	private global::Gtk.Action HowToUseAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Image image1;

	private global::Gtk.Label dsiplabel;

	private global::Gtk.Entry targetIP;

	private global::Gtk.Button locateDSbtn;

	private global::Gtk.Label ComputerIPLabel;

	private global::Gtk.Entry hostipEntry;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.Button BoopBtn;

	private global::Gtk.Button PickFiles;

	private global::Gtk.Entry Port;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.SettingsAction = new global::Gtk.Action("SettingsAction", global::Mono.Unix.Catalog.GetString("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Settings");
		w1.Add(this.SettingsAction, null);
		this.HowToUseAction = new global::Gtk.Action("HowToUseAction", global::Mono.Unix.Catalog.GetString("How to use"), null, null);
		this.HowToUseAction.ShortLabel = global::Mono.Unix.Catalog.GetString("How to use");
		w1.Add(this.HowToUseAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("BoopGTK");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("icon.snek");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.DefaultWidth = 500;
		this.DefaultHeight = 700;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='SettingsAction' action='SettingsAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='HowToUseAction' action='HowToUseAction'/><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.WidthRequest = 400;
		this.menubar1.Name = "menubar1";
		this.fixed1.Add(this.menubar1);
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.fixed1.Add(this.hseparator1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator1]));
		w3.X = 68;
		w3.Y = 266;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("logo.snek");
		this.fixed1.Add(this.image1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image1]));
		w4.X = 25;
		w4.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dsiplabel = new global::Gtk.Label();
		this.dsiplabel.Name = "dsiplabel";
		this.dsiplabel.LabelProp = global::Mono.Unix.Catalog.GetString("DS IP Adress:");
		this.fixed1.Add(this.dsiplabel);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dsiplabel]));
		w5.X = 26;
		w5.Y = 268;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.targetIP = new global::Gtk.Entry();
		this.targetIP.TooltipMarkup = "Open FBI\nSelect Remote Install\nSelect Receive urls\nEnter the IP without the port";
		this.targetIP.CanFocus = true;
		this.targetIP.Name = "targetIP";
		this.targetIP.IsEditable = true;
		this.targetIP.InvisibleChar = '•';
		this.fixed1.Add(this.targetIP);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.targetIP]));
		w6.X = 123;
		w6.Y = 262;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.locateDSbtn = new global::Gtk.Button();
		this.locateDSbtn.CanFocus = true;
		this.locateDSbtn.Name = "locateDSbtn";
		this.locateDSbtn.UseUnderline = true;
		this.locateDSbtn.Label = global::Mono.Unix.Catalog.GetString("Find IP");
		this.fixed1.Add(this.locateDSbtn);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.locateDSbtn]));
		w7.X = 290;
		w7.Y = 261;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ComputerIPLabel = new global::Gtk.Label();
		this.ComputerIPLabel.Name = "ComputerIPLabel";
		this.ComputerIPLabel.LabelProp = global::Mono.Unix.Catalog.GetString("PC IP Adress:");
		this.fixed1.Add(this.ComputerIPLabel);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ComputerIPLabel]));
		w8.X = 23;
		w8.Y = 221;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hostipEntry = new global::Gtk.Entry();
		this.hostipEntry.CanFocus = true;
		this.hostipEntry.Name = "hostipEntry";
		this.hostipEntry.Text = global::Mono.Unix.Catalog.GetString("192.168.x.x");
		this.hostipEntry.IsEditable = false;
		this.hostipEntry.InvisibleChar = '•';
		this.fixed1.Add(this.hostipEntry);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hostipEntry]));
		w9.X = 121;
		w9.Y = 214;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 375;
		this.GtkScrolledWindow.HeightRequest = 200;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.nodeview1.EnableSearch = false;
		this.nodeview1.Reorderable = true;
		this.GtkScrolledWindow.Add(this.nodeview1);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w11.X = 13;
		w11.Y = 354;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BoopBtn = new global::Gtk.Button();
		this.BoopBtn.WidthRequest = 300;
		this.BoopBtn.CanFocus = true;
		this.BoopBtn.Name = "BoopBtn";
		this.BoopBtn.UseUnderline = true;
		this.BoopBtn.Label = global::Mono.Unix.Catalog.GetString("BOOP");
		this.fixed1.Add(this.BoopBtn);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.BoopBtn]));
		w12.X = 46;
		w12.Y = 556;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PickFiles = new global::Gtk.Button();
		this.PickFiles.WidthRequest = 200;
		this.PickFiles.CanFocus = true;
		this.PickFiles.Name = "PickFiles";
		this.PickFiles.UseUnderline = true;
		this.PickFiles.Label = global::Mono.Unix.Catalog.GetString("Pick Files");
		this.fixed1.Add(this.PickFiles);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.PickFiles]));
		w13.X = 93;
		w13.Y = 313;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Port = new global::Gtk.Entry();
		this.Port.WidthRequest = 60;
		this.Port.CanFocus = true;
		this.Port.Name = "Port";
		this.Port.Text = global::Mono.Unix.Catalog.GetString("8080");
		this.Port.IsEditable = true;
		this.Port.InvisibleChar = '•';
		this.fixed1.Add(this.Port);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Port]));
		w14.X = 287;
		w14.Y = 213;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.locateDSbtn.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.locateDSbtn.Clicked += new global::System.EventHandler(this.BtnFindIP_Clicked);
		this.BoopBtn.Clicked += new global::System.EventHandler(this.OnBoopBtnClicked);
		this.PickFiles.Clicked += new global::System.EventHandler(this.OnPickFilesClicked);
	}
}
