
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action SettingsAction;

	private global::Gtk.Action HowToUseAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Image image1;

	private global::Gtk.Entry hostipEntry;

	private global::Gtk.Label ComputerIPLabel;

	private global::Gtk.Entry targetIP;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.SettingsAction = new global::Gtk.Action("SettingsAction", global::Mono.Unix.Catalog.GetString("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Settings");
		w1.Add(this.SettingsAction, null);
		this.HowToUseAction = new global::Gtk.Action("HowToUseAction", global::Mono.Unix.Catalog.GetString("How to use"), null, null);
		this.HowToUseAction.ShortLabel = global::Mono.Unix.Catalog.GetString("How to use");
		w1.Add(this.HowToUseAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("BoopGTK");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("BoopGTK.snekicon.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.DefaultWidth = 400;
		this.DefaultHeight = 500;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='SettingsAction' action='SettingsAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='HowToUseAction' action='HowToUseAction'/><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.WidthRequest = 400;
		this.menubar1.Name = "menubar1";
		this.fixed1.Add(this.menubar1);
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.fixed1.Add(this.hseparator1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator1]));
		w3.X = 68;
		w3.Y = 266;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("BoopGTK.Boop1.png");
		this.fixed1.Add(this.image1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image1]));
		w4.X = 25;
		w4.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hostipEntry = new global::Gtk.Entry();
		this.hostipEntry.CanFocus = true;
		this.hostipEntry.Name = "hostipEntry";
		this.hostipEntry.Text = global::Mono.Unix.Catalog.GetString("192.168.x.x");
		this.hostipEntry.IsEditable = false;
		this.hostipEntry.InvisibleChar = '•';
		this.fixed1.Add(this.hostipEntry);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hostipEntry]));
		w5.X = 216;
		w5.Y = 212;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ComputerIPLabel = new global::Gtk.Label();
		this.ComputerIPLabel.Name = "ComputerIPLabel";
		this.ComputerIPLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Computer IP Adress:");
		this.fixed1.Add(this.ComputerIPLabel);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ComputerIPLabel]));
		w6.X = 66;
		w6.Y = 217;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.targetIP = new global::Gtk.Entry();
		this.targetIP.CanFocus = true;
		this.targetIP.Name = "targetIP";
		this.targetIP.IsEditable = true;
		this.targetIP.InvisibleChar = '•';
		this.fixed1.Add(this.targetIP);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.targetIP]));
		w7.X = 223;
		w7.Y = 264;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
